services:
    apache:
        container_name: "${COMPOSE_PROJECT_NAME}_apache"
        build:
            context: ./apache
            dockerfile: Dockerfile
            args:
                PUID: "${PUID}"
                PGID: "${PGID}"
                DEFAULT_TIMEZONE: "${DEFAULT_TIMEZONE}"
                APACHE_SYSTEM_PACKAGES: "${APACHE_SYSTEM_PACKAGES}"
                APACHE_MODULES_ENABLED: "${APACHE_MODULES_ENABLED}"
                APACHE_MODULES_DISABLED: "${APACHE_MODULES_DISABLED}"
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=${TRAEFIK_NETWORK_NAME}"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.entrypoints=web"
            - "traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.${TRAEFIK_HOSTNAME}`)"
        networks:
            - private
            - public
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - "./apache/apache2.conf:/etc/apache2/apache2.conf:delegated"
            - "${DOCUMENT_ROOT_HOST_PATH}:${DOCUMENT_ROOT_CONTAINER_PATH}:delegated"
            - "./apache/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:delegated"

    php-fpm:
        container_name: "${COMPOSE_PROJECT_NAME}_php-fpm"
        build:
            context: php-fpm
            dockerfile: Dockerfile
            args:
                PUID: "${PUID}"
                PGID: "${PGID}"
                DEFAULT_TIMEZONE: "${DEFAULT_TIMEZONE}"
                PHP_FPM_VERSION: "${PHP_FPM_VERSION}"
                PHP_FPM_SYSTEM_PACKAGES: "${PHP_FPM_SYSTEM_PACKAGES}"
                PHP_FPM_PEAR_PACKAGES: "${PHP_FPM_PEAR_PACKAGES}"
                PHP_FPM_PECL_PACKAGES: "${PHP_FPM_PECL_PACKAGES}"
                PHP_FPM_COMPOSER_INSTALL: "${PHP_FPM_COMPOSER_INSTALL}"
        depends_on:
            - apache
        networks:
            - private
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - "./php-fpm/xdebug-cli.ini:/etc/php/${PHP_FPM_VERSION}/cli/conf.d/zzzz_xdebug.ini:delegated"
            - "./php-fpm/php-cli.ini:/etc/php/${PHP_FPM_VERSION}/cli/conf.d/zzzz_custom.ini:delegated"
            - "./php-fpm/php.ini:/etc/php/${PHP_FPM_VERSION}/fpm/conf.d/zzzz_custom.ini:delegated"
            - "./php-fpm/php-fpm.conf:/etc/php/${PHP_FPM_VERSION}/fpm/php-fpm.conf:delegated"
            - "${DOCUMENT_ROOT_HOST_PATH}:${DOCUMENT_ROOT_CONTAINER_PATH}:delegated"
            - "./php-fpm/xdebug.ini:/etc/php/${PHP_FPM_VERSION}/fpm/conf.d/zzzz_xdebug.ini:delegated"

    mariadb:
        container_name: "${COMPOSE_PROJECT_NAME}_mariadb"
        image: "mariadb:${MARIADB_VERSION}"
        environment:
            - TZ=${DEFAULT_TIMEZONE}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASSWORD}
        networks:
            - private
            - public
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - published: "${MARIADB_PUBLISHED_PORT}"
              target: 3306
              protocol: tcp
              mode: host
        volumes:
            - "mariadb-data:/var/lib/mysql"
            - "./mariadb/my.cnf:/etc/mysql/my.cnf:delegated"
        healthcheck:
            test: ["CMD", "mariadb-admin" ,"ping", "-h", "127.0.0.1", "-u", "root", "-p$$MARIADB_ROOT_PASSWORD"]
            interval: 2s
            timeout: 20s
            retries: 10
    backup:
        container_name: "${COMPOSE_PROJECT_NAME}_backup"
        build:
            context: backup
            dockerfile: Dockerfile
        depends_on:
            mariadb:
                condition: service_healthy
        environment:
            - PUID=${PUID}
            - PGID=${PGID}
            - TZ=${DEFAULT_TIMEZONE}
            - BACKUP_ENABLED=${BACKUP_ENABLED}
            - BACKUP_PRUNE_AGE_ENABLED=${BACKUP_PRUNE_AGE_ENABLED}
            - BACKUP_PRUNE_AGE_THRESHOLD=${BACKUP_PRUNE_AGE_THRESHOLD}
            - BACKUP_PRUNE_NEWEST_ENABLED=${BACKUP_PRUNE_NEWEST_ENABLED}
            - BACKUP_PRUNE_NEWEST_THRESHOLD=${BACKUP_PRUNE_NEWEST_THRESHOLD}
            - MARIADB_HOSTNAME=${COMPOSE_PROJECT_NAME}_mariadb
            - MARIADB_DATABASE=${MARIADB_DATABASE}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - private
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "${BACKUP_HOST_PATH}:/var/backup/data"
networks:
    private:
    public:
        name: "${TRAEFIK_NETWORK_NAME}"
        external: true
volumes:
    mariadb-data:

